name: beacon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.3
  fluttertoast: ^8.0.3
  geolocator: ^7.0.1
  google_maps_flutter: ^2.0.2
  intl: ^0.17.0
  flutter_picker: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  esys_flutter_share: ^1.0.2
  modal_progress_hud: ^0.1.3
  duration_picker: ^1.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: FuturaBold
      fonts:
        - asset: fonts/futura_bold.otf